-- Tabla de reportes de fraude (equivalente a la migración InitialCreate)
CREATE TABLE IF NOT EXISTS frauds (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ImpostorDetails" character varying(2000) NOT NULL,
    "ContactInfo" character varying(500) NOT NULL,
    "Comments" character varying(4000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_frauds" PRIMARY KEY ("Id")
);
